### ISSUE TITLE
Unable to load - The column 'StoryPoints' of the table wasn't found

### ISSUE THREAD

**Issue by nbrown02** [colindembovsky/azdo-pbi#1]
Just tried loading with Epic / Feature / Product Backlog Item hierarchy. I had the following issues on the following tables:

Epics (Table) - The column 'StoryPoints' of the table wasn't found
Features (Table) - The column 'StoryPoints' of the table wasn't found
Stories (Table) - The column 'StoryPoints' of the table wasn't found

Once they're removed it loads ok though 👍

**Comment by colindembovsky** [comment]
Thanks @nbrown02 - we were going to make the charts work with story points instead of count when we started. Of course this field only exists on the Agile template, so if you're not using Agile you'll get this error.
